export const BASE_URL =
  'https://svs-studio-dev.apps.devsaibocp.saibnet2.saib.com'
export const FakeJwtToken =
  'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI2NDgxOTZhNTM5OTQ2NDM2ODA4M2EwMTUiLCJzdWIiOiIwNTY3MTEzNTM0Iiwicm9sZXMiOlsiT05CT0FSRElORyJdLCJpc3MiOiJjb20uc2FpYi52ZW50dXJlcy5hdXRoIiwiYXVkIjoiY29tLnNhaWIudmVudHVyZXMuYXV0aCIsImV4cCI6MTY4NjIxNzkyNCwiaWRlbnRpdHkiOiIyNTQ1MzEyOTMyIiwicGhvbmVfbnVtYmVyIjoiMDU2NzExMzUzNCJ9.ETQ8xpbv1U9xC5W2KH23OhEXSma0aWR1F44OqRytzfKIJeCGdZ9qal94c8_ppgukAnEvMgLmPwOigp97QTtOqA'
