export const NafaathLogo = require('./NafaathLogo.png')
export const WarnIconImg = require('./warnIcon.png')
export const EuroFlag = require('./euro-country-flag.png')
export const Promotion1 = require('./promotion1.png')
export const Promotion2 = require('./promotion2.png')
export const Promotion3 = require('./promotion3.png')
export const Shadow = require('./shadow.png')
