# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    #increment_build_number(xcodeproj: "travelcard.xcodeproj")

    build_app(
      scheme: "travelcard", 
      workspace: "travelcard.xcworkspace", 
      configuration: "Release",
      clean: true,
      export_method: "ad-hoc",
      export_options: {
        provisioningProfiles: {
            CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier) => "match AdHoc com.saib.venture.travel"
        }
      },
      build_path: "./builds",
      output_directory: "./builds"
    )

    zealot(
      endpoint: "https://localhost",
      token: "320bacf980e20e7b058be2d77154dc53",
      channel_key: "a455bd5544a721e2d528bec8d26130d2",
      release_type: "ad-hoc",
      verify_ssl: "false"
    )
  end
end
